-- Criação da tabela contato
CREATE TABLE IF NOT EXISTS tipo_contato (
    idContato GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricaoContato TEXT NOT NULL
);

-- Alteração da tabela telefone para adicionar a chave estrangeira idContato
ALTER TABLE IF EXISTS telefone
ADD COLUMN IF NOT EXISTS idContato INTEGER DEFAULT 0,
ADD CONSTRAINT fk_tipoContato_telefone FOREIGN KEY (idContato) REFERENCES tipoContato(idContato);
